{
 "title": "SAP NetWeaver",
 "description": "Shows detailed stats of a SAP NetWeaver cluster. Brought to you by SUSE.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Start Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sap_start_service_instances" }
   ]
  },
  {
   "title": "Processes",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "sap_start_service_processes" }
   ]
  },
  {
   "title": "Instance Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sap_start_service_instances == 1)",
     "legendFormat": "GRAY"
    },
    {
     "expr": "count(sap_start_service_instances == 2)",
     "legendFormat": "GREEN"
    },
    {
     "expr": "count(sap_start_service_instances == 3)",
     "legendFormat": "YELLOW"
    },
    {
     "expr": "count(sap_start_service_instances == 4)",
     "legendFormat": "RED"
    }
   ]
  },
  {
   "title": "Process Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sap_start_service_processes == 1)",
     "legendFormat": "GRAY"
    },
    {
     "expr": "count(sap_start_service_processes == 2)",
     "legendFormat": "GREEN"
    },
    {
     "expr": "count(sap_start_service_processes == 3)",
     "legendFormat": "YELLOW"
    },
    {
     "expr": "count(sap_start_service_processes == 4)",
     "legendFormat": "RED"
    }
   ]
  },
  { "title": "Enqueue Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Lock Table Entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sap_enqueue_server_locks_now", "legendFormat": "Locks" },
    { "expr": "sap_enqueue_server_owner_now", "legendFormat": "Lock owners" },
    {
     "expr": "sap_enqueue_server_arguments_now",
     "legendFormat": "Lock arguments"
    }
   ]
  },
  {
   "title": "Requests / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sap_enqueue_server_enqueue_requests[5m])",
     "legendFormat": "Lock"
    },
    {
     "expr": "rate(sap_enqueue_server_enqueue_rejects[5m])",
     "legendFormat": "Rejected"
    },
    {
     "expr": "rate(sap_enqueue_server_dequeue_requests[5m])",
     "legendFormat": "Release"
    },
    {
     "expr": "rate(sap_enqueue_server_dequeue_all_requests[5m])",
     "legendFormat": "LUW release"
    },
    {
     "expr": "rate(sap_enqueue_server_cleanup_requests[5m])",
     "legendFormat": "Server release"
    }
   ]
  },
  {
   "title": "Errors / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sap_enqueue_server_enqueue_errors[5m])",
     "legendFormat": "Lock"
    },
    {
     "expr": "rate(sap_enqueue_server_dequeue_errors[5m])",
     "legendFormat": "Release"
    }
   ]
  },
  { "title": "Work Process Dispatcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Dispatcher Queue Depth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sap_dispatcher_queue_now", "legendFormat": "{{type}} {{instance_name}}" }
   ]
  },
  {
   "title": "Dispatcher Queue Depth High",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sap_dispatcher_queue_high", "legendFormat": "{{type}} {{instance_name}}" }
   ]
  },
  {
   "title": "Dispatcher Queue Depth Threshold",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sap_dispatcher_queue_max", "legendFormat": "{{type}} {{instance_name}}" }
   ]
  },
  {
   "title": "Dispatcher Queues Reads / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sap_dispatcher_queue_reads[5m])",
     "legendFormat": "{{type}} {{instance_name}}"
    }
   ]
  },
  {
   "title": "Dispatcher Queue Writes / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sap_dispatcher_queue_writes[5m])",
     "legendFormat": "{{type}} {{instance_name}}"
    }
   ]
  }
 ]
}